### ISSUE TITLE
Request - set terraform output as environment variables

### ISSUE THREAD

**Issue by scott-doyland-burrows** [hashicorp/setup-terraform#101]
Hi,

This is a request to allow the output of ```terraform output``` be set as environment variables.

For example, if my output is:

```myvar = "somevalue"```

then I'd like to be able to pick up ```myvar``` as an environment variable.

This feature is available in an Azure DevOps extension:

https://github.com/charleszipp/azure-pipelines-tasks-terraform

This is really useful when the terraform output need to be passed into non-terraform jobs running in the same pipeline.

**Comment by russmac** [comment]
@scott-doyland-burrows This can be achieved using step and job outputs although the syntax (GHA) is a bit awful, However the main reason I'm mentioning this is the env vars have very limited capacity to store output. In my circumstance I exhausted 3 different mechanisms which all had the same length limitations and cut off my output. If your output is verbose or from a large or more then 1 workspace you may be better sending the data to a datastore, which can be linked in the PR or similar. GHA artifacts are useless for this unfortunately as the link is determined (and non guessable) on workflow completion.

**Comment by scott-doyland-burrows** [comment]
I actually got this working using the YAML like this:

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - run: terraform apply -auto-approve
      - run: echo "ec2_instance_id=`terraform output -raw instance_id`" >> $GITHUB_ENV

This was fine for my needs.  And I could then set the env var as an artifact if needed and pass to other jobs in the same workflow.

Being able to pass env vars between jobs would be good though, rather than having to use artifacts.

**Comment by russmac** [comment]
> Being able to pass env vars between jobs would be good though, rather than having to use artifacts.

You can: https://github.blog/changelog/2020-04-15-github-actions-new-workflow-features/

**Comment by bflad** [comment]
Hi @scott-doyland-burrows  👋 Thank you for this feature request. We are intending this GitHub Action to be used for installing Terraform and optionally configuring its CLI configuration file. We do not intend to support manipulating Terraform command outputs or other enhancements based on the calling of actual Terraform commands with this particular action, therefore I'm going to close this issue. If there is still a need for this type of functionality though, someone could theoretically implement a new GitHub Action that does what is proposed.
