### ISSUE TITLE
When I attempt to run Terraform Init with multiple '-backend-config' I get a 'Too many command line arguments.' Error

### ISSUE THREAD

**Issue by eranjbarSuncor** [hashicorp/setup-terraform#106]
I am using the github action to setup my terraform and then use Terraform Init like so:

```
- name: Terraform init
      run: |
          terraform init \
                    -backend-config="key=${ENV}.terraform.tfstate" \
                    -backend-config="resource_group_name=${resource_group}" \ 
                    -backend-config="storage_account_name=${storage_account_name}" 
```

But I am getting a the `Too many command line arguments. Did you mean to use -chdir?` error. I have tried to follow the documentation for using -backend-config here: https://www.terraform.io/docs/language/settings/backends/configuration.html#partial-configuration

I even have the same number of arguments as the example but it does not work... Am I missing something? This seems like it's an issue with terraform or the github action to install terraform

I have tried this with two `-backend-config` arguments and it works fine

**Comment by kclarkey** [comment]
> - name: Terraform init
>       run: |
>           terraform init \
>                     -backend-config="key=${ENV}.terraform.tfstate" \
>                     -backend-config="resource_group_name=${resource_group}" \ 
>                     -backend-config="storage_account_name=${storage_account_name}"

Assuming this is a direct copy of what you have locally, there appears to be a trailing space after the `\` in your second `-backend-config` parameter. Remove that and you should be in better shape.

**Comment by bflad** [comment]
Hi @eranjbarSuncor 👋 Hopefully @kclarkey's answer above resolved your issue. If you have further questions, my best recommendation would be to submit a topic in the [Terraform section of HashiCorp Discuss](https://discuss.hashicorp.com/c/terraform-core/27), where there are many more people asking and answering usage questions such as these.
