### ISSUE TITLE
setup-terraform hangs

### ISSUE THREAD

**Issue by fnmarquez** [hashicorp/setup-terraform#124]
I am using a self hosted runner in GHES to run this
```
      - uses: actions/setup-terraform@v1.3.2
        with:
          terraform_version: 0.14.10
```

but the installation never completes.
I have already tried enabling verbose log for the runner but it doesn't give information about where it is hanged.

```
5h 6m 23s
Run actions/setup-terraform@v1.3.2
  with:
    terraform_version: 0.14.10
    cli_config_credentials_hostname: app.terraform.io
    terraform_wrapper: ***
```

Please let me know if you need more information to understand what is happening.

**Comment by bflad** [comment]
Hi @fnmarquez 👋 Thank you for this bug report and sorry it was never responded to in a timely manner. Hopefully this issue has been resolved in the meantime. If its not resolved while using recent versions of the action, please raise a fresh bug report and we can take a look.
