### ISSUE TITLE
Publish docker image for use in github actions

### ISSUE THREAD

**Issue by mrchief** [hashicorp/setup-terraform#137]
Now that github actions can use docker images directly, `uses: docker://hashicorp/setup-terraform:latest`, it'd help speed up the builds if this action can be published to GHCR or Dockerhub as a prebuilt image.

**Comment by bflad** [comment]
Hi @mrchief 👋 Thank you for submitting this feature request. We do not intend to release a Docker image for this action. If you need a specific version of Terraform via Docker, there are the [`hashicorp/terraform` Docker images](https://hub.docker.com/r/hashicorp/terraform) available which can save the step of selecting a version via this action.
