### ISSUE TITLE
Has this project been abandoned?

### ISSUE THREAD

**Issue by ap0phi5** [hashicorp/setup-terraform#138]
At the time of writing, the lead maintainer seems to have left HashiCorp and a number of good PRs coming in haven't been reviewed. There doesn't seem to have been a merge to main since June.

@nywilken @DanielMSchmidt  Anyway we can get this resuscitated? Actions is a great way of running TF and it would be a shame to let this go stale!

**Comment by ap0phi5** [comment]
cc @aeschright

**Comment by jpogran** [comment]
Hi @ap0phi5, thanks for inquiring about the status of the project. It has not been abandoned, it's just something we've had to prioritize against other work being done. We are discussing a review schedule for the outstanding PRs and working on a release cadence for this project. We'll update here when that is decided.

**Comment by ap0phi5** [comment]
Hi @jpogran,
If you folks decide that you have too many resourcing constraints, perhaps you could suggest to see if GitHub themselves would be willing to host this here? https://github.com/integrations

**Comment by breathingdust** [comment]
Hi @ap0phi5 👋  

The good news is that the Terraform DevEx team will strongly own this project going forward, though the idea of it becoming an official GitHub Integration is an interesting one! The DevEx team is fairly new in charter and is going through some changes internally, so it may take a little time for them to pick this up and for you to see movement.

Thanks for checking in!

**Comment by ap0phi5** [comment]
Hello @breathingdust, @jpogran,

Sounds good, just checking with you guys again!  Selfishly, a great start would be this issue- there are a lot of folks affected and a PR ready for review...? https://github.com/hashicorp/setup-terraform/issues/17 😁

**Comment by jpogran** [comment]
Hey @ap0phi5, I've picked up that PR and added some commits to get it passing CI. Going to run it through some tests and make sure my changes haven't broken anything. I reviewed the open PRs and most should close with the dependencies updated by this PR. I added some comments on the other open PRs and will circle back on those. Next up will be looking through the issues and triaging them.
