### ISSUE TITLE
Catch 22 when using multiple workspaces

### ISSUE THREAD

**Issue by ansman** [hashicorp/setup-terraform#140]
We are using multiple workspaces for our project, one per environment.

When we try to use the terraform CLI in GH Actions we end up in a catch 22 scenario. We cannot run `terraform init` because it prompts us for a workspace and the action hangs until killed and we cannot use `terraform workspace select <workspace>` before running `terraform init`. How are you meant to use this action with multiple workspaces?

**Comment by ansman** [comment]
Turns out there is a pretty hidden env var you can set during init called `TF_WORKSPACE`: https://learn.hashicorp.com/tutorials/terraform/automate-terraform

**Comment by dvasdekis** [comment]
Would be so nice if this was added to the docs and examples! I can give it a go if you're accepting PRs?
