### ISSUE TITLE
Actions download latest-latest terraform

### ISSUE THREAD

**Issue by szymonrychu** [hashicorp/setup-terraform#16]
Current action downloads latest terraform binary regardless of it's stability- ie it downloads latest even it it's a beta release.
Which broke ~nearly-prod environment and required to destroy and reapply two major components in our infra and rotation of AWS IAM credentials for bot users used to apply the code.
Please fix it asap.

**Comment by ZebraFlesh** [comment]
Yep, now my state files are updated to 0.13.0 due to automation. Very not happy about this.

**Comment by cdaniluk** [comment]
Narrowly avoided a similar sad fate on this, solely because we were using an experimental feature in 0.12 that is no longer experimental in 0.13, which caused my plan to fail. This is crazy dangerous.

**Comment by chenrui333** [comment]
To people who suffering with this issue, please actively lockdown the version (so that the change is more controllable).

In `setup-terraform` action:
```
steps:
- uses: hashicorp/setup-terraform@v1
  with:
    terraform_version: 0.12.25
```

In `provider.tf` (or any file that you have `terraform {` declared):

```
terraform {
  required_version = "= 0.12.25"
```
