### ISSUE TITLE
Action fails behind the proxy

### ISSUE THREAD

**Issue by ytsarev** [hashicorp/setup-terraform#17]
We are using self-hosted runners and trying to execute the action behind the corporate proxy

It fails with
```
Run hashicorp/setup-terraform@v1
##[error]Failed to fetch version metadata. FetchError: request to https://releases.hashicorp.com/terraform/index.json failed, reason: connect ETIMEDOUT 151.101.193.183:443
##[error](s || "").replace is not a function
```

I tried to declare standard http_proxy variables with
```
        env:
          http_proxy: http://<proxy_adress>:<port>
          https_proxy: http://<proxy_adress>:<port>
```

It didn't help apparently due to the node's `fetch` specifics which is used at https://github.com/hashicorp/setup-terraform/blob/168ae737806ba2b58d7733858cc173ff44d7f284/lib/setup-terraform.js#L43

Related upstream issue https://github.com/node-fetch/node-fetch/issues/79

**Comment by Manu206** [comment]
Is there any update on this?
The mentioned code changed and the fetch is not visible anymore. However I'm still facing issues behind a proxy even with passing https_proxy and http_proxy.

```
Error: Error: getaddrinfo ENOTFOUND releases.hashicorp.com
Error: getaddrinfo ENOTFOUND releases.hashicorp.com
```

**Comment by L4R5** [comment]
+1
