### ISSUE TITLE
Latest version between marketplace and releases out of sync

### ISSUE THREAD

**Issue by jlosito** [hashicorp/setup-terraform#171]
It appears that the latest version that the marketplace believes this action has is version 1.2.1, even though 1.3.2 is clearly available at the time of writing. I personally have dependabot notifying me of any version bumps, and it also knows that version 1.3.2 is available. It would be nice if the marketplace was update to date though.

https://github.com/marketplace/actions/hashicorp-setup-terraform

![Screen Shot 2022-03-31 at 1 02 08 PM](https://user-images.githubusercontent.com/25142529/161110433-b18e7c51-c4e9-479f-974c-f764bb87f625.png)

**Comment by jpogran** [comment]
Thanks for the report. We're working with GitHub to get this synced properly.

**Comment by ksatirli** [comment]
Hello @jlosito, thank you for reporting this!

We've released version `1.4.0` and made it available on https://github.com/marketplace/actions/hashicorp-setup-terraform.
