### ISSUE TITLE
Got forbidden error with v1.3.2

### ISSUE THREAD

**Issue by chenrui333** [hashicorp/setup-terraform#172]
Not sure what is going on, but just run into forbidden error
![image](https://user-images.githubusercontent.com/1580956/161306582-de7ff77f-dbe4-4439-bc46-e59b625c240f.png)

This is my config
```
      - uses: hashicorp/setup-terraform@v1.3.2
        with:
          terraform_version: 1.0.0
```

**Comment by HongLi26** [comment]
Same here, we could apply with same code in the morning but now it is forbidden. any bugs?

**Comment by chenrui333** [comment]
I think this is blocked by #170 
cc @jpogran (any way to expedite that PR?)

**Comment by chenrui333** [comment]
For whom seeing this issue, revert all the github action upgrades would do the job (at least for me)

**Comment by sabernal** [comment]
Same here, we haven't done any upgrades recently

**Comment by chenrui333** [comment]
> Same here, we haven't done any upgrades recently

like any github actions? all my workflows are working fine now.

**Comment by sabernal** [comment]
yeah.. we did a rerun recently and its working again, pretty weird

**Comment by chenrui333** [comment]
aha, let me re-commit my action upgrades.

**Comment by chenrui333** [comment]
yeah, it is `api.terraform.com` issue. Should be good for everyone know. Closing this report.

**Comment by chenrui333** [comment]
Related incident report, https://status.hashicorp.com/incidents/fhvlq3hngf6h
