### ISSUE TITLE
Unable to Use Custom Provider in Current Working Directory

### ISSUE THREAD

**Issue by picatz** [hashicorp/setup-terraform#22]
I was [unable](https://github.com/picatz/terraform-provider-port-scan/pull/6/commits/dd6b9d999b50c4ccdbf1fc328222ddd038686cfa) to use a custom provider [built](https://github.com/picatz/terraform-provider-port-scan/pull/6/commits/dd6b9d999b50c4ccdbf1fc328222ddd038686cfa#diff-128469c2fd54cf32412f10096b91495aR46) in my current working directory. But, I was able to run it successfully on my local machine, and in GitHub Actions [after](https://github.com/picatz/terraform-provider-port-scan/pull/6/commits/de368b99ea0463cbd5832a46175ca27bfe2b2dfe) installing Terraform manually. However, I'd really like to use this action instead! 😺 

## Error

Using [this](https://github.com/picatz/terraform-provider-port-scan/actions/runs/140247840/workflow) workflow file I got the following error for the "Terraform Init" step:

```console
Run terraform init
/home/runner/work/_temp/814bb1c2-7670-4133-aeae-b273f2121049/terraform-bin init

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/port...

Error: Failed to install provider

Error while installing hashicorp/port: provider registry registry.terraform.io
does not have a provider named registry.terraform.io/hashicorp/port

##[error]Terraform exited with code 1.
##[error]Process completed with exit code 1.
```

🤔  Is there a trick for getting custom providers to work with this action, or a bug that's preventing Terraform from searching in my current working directory for providers?

**Comment by sudomateo** [comment]
I believe this was because the action was installing Terraform 0.13 beta 1 when `terraform_version` was set to `latest`. Would you be able to try again with action version `1.1.0`?

**Comment by kevin-shelaga** [comment]
@picatz @sudomateo 

```
- uses: hashicorp/setup-terraform@v1.1.0
```

**Comment by picatz** [comment]
Thank you @sudomateo and @kevin-shelaga!

Using `hashicorp/setup-terraform@v1.1.0` worked like a charm. 🍀
