### ISSUE TITLE
Error: Error: Unexpected HTTP response: 404

### ISSUE THREAD

**Issue by landradetractian** [hashicorp/setup-terraform#228]
Today a few hours ago I started to receive this title error in all setup terraform steps in my workflows in Github.

![image](https://user-images.githubusercontent.com/97478093/181293654-ea1d9e8a-49c4-4f92-8043-07cdcd4c4727.png)

workflows step snippet code:

```
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
```

**Comment by landradetractian** [comment]
This is happening using self-hosted runners and shared runners, same error.

**Comment by AL1067007** [comment]
Thanks for opening the issue, we have the same problem on our side

**Comment by landradetractian** [comment]
Thanks for the response, pining the version right now!

**Comment by kellycastrof** [comment]
Specifying that version solved the problem, thanks!

**Comment by mendaxfz** [comment]
```
Run hashicorp/setup-terraform@v1
(node:2155) [DEP0005]  DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Error: Error: Request failed with status code 404
Error: Request failed with status code 404
```

Getting same error with v1

**Comment by bflad** [comment]
Hi again folks 👋 The Terraform release asset issue should be resolved now and GitHub Actions workflows should start working again without the workarounds I mention above. Can anyone confirm this is no longer an issue?

If there are still lingering issues, please ensure there are no proxies or caching between where your workflow is running and https://releases.hashicorp.com/ or verify that any caching in those places has been cleared so a new fetch is performed.

**Comment by kellycastrof** [comment]
It's working now, thanks!

**Comment by mendaxfz** [comment]
Working now

**Comment by bflad** [comment]
Excellent to hear. I'm going to close this issue now with the hope that everything is cleared up now, but please reach out if that is not the case.
