### ISSUE TITLE
Buffer() is deprecated due to security and usability issues. 

### ISSUE THREAD

**Issue by thomashutcheson-msm** [hashicorp/setup-terraform#229]
Hi 
We have just started getting an issue with setup-terraform stating that Buffer() func is deprecated.

Run hashicorp/setup-terraform@v1
(node:256111) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Error: Error: Unexpected HTTP response: 404

**Comment by kellycastrof** [comment]
It's a problem with a release, check this issue https://github.com/hashicorp/setup-terraform/issues/228
