### ISSUE TITLE
Unable to get recent versions with latest tag

### ISSUE THREAD

**Issue by laurenmcdonald-kr** [hashicorp/setup-terraform#23]
When setting latest (or leaving it off), the action step is only pulling version 0.12.26:
Run hashicorp/setup-terraform@v1
Latest version is 0.12.26

Workflow pipeline yml:
   - name: "Terraform"
     uses: hashicorp/setup-terraform@v1
     with:
      terraform_version: latest

Run terraform init \  ...
Initializing modules... 
- vm in vm 
 
Error: Unsupported Terraform Core version 
 
This configuration does not support Terraform version 0.12.26. To proceed, 
either choose another supported Terraform version or update the root module's 
version constraint. Version constraints are normally set for good reason, so 
updating the constraint may lead to other errors or unexpected behavior. 
 
##[error]Terraform exited with code 1. 
##[error]Process completed with exit code 1.

This was working yesterday without specifying a version. Wondering if the push last night affected this? Also tried to specify the version via the README instructions and get: (s || "").replace is not a function

@sudomateo

**Comment by sudomateo** [comment]
`v1.1.0` introduced a change where setting `terraform_version` to `latest` will only pull the - latest stable release (i.e. not `-beta1` or the like).

**Comment by aeschright** [comment]
Closing as fixed.
