### ISSUE TITLE
Failing with 404

### ISSUE THREAD

**Issue by leehanchung** [hashicorp/setup-terraform#231]
Hi, 

Getting 404 running setup-terraform actions thats first referenced in https://github.com/hashicorp/setup-terraform/issues/195.

```Run hashicorp/setup-terraform@v2
(node:8394) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Error: Error: Unexpected HTTP response: 404
Error: Unexpected HTTP response: 404
```

I think this was related to the recent Releases API migration. If this occurs again please open a new issue.

_Originally posted by @jpogran in https://github.com/hashicorp/setup-terraform/issues/195#issuecomment-1130091724_

**Comment by bflad** [comment]
Hi @leehanchung 👋 Is this issue still occurring for you if you re-run the affected workflow? There was a [Terraform release asset incident this morning](https://status.hashicorp.com/incidents/1jw0q79c6cd5) which would have generated errors such as these earlier today. Please refer to #228 for additional details around timing and suggestions.

**Comment by leehanchung** [comment]
Works now. Thank you~!
