### ISSUE TITLE
`terraform show` fails with the wrapper, when output is piped into another command

### ISSUE THREAD

**Issue by jpluscplusm** [hashicorp/setup-terraform#307]
`terraform show` is (relatively!) unique among terraform's commands, in that it can't **do** anything. Its only purpose is to output info.

Thus, when used inside a CI environment, it's pretty likely that its output will be piped into another command for processing (decoration; testing; etc).

When the wrapper is in place, piping `terraform show` output into anything fails, with IO:pipe-ish error messages. Apologies that I don't have them to hand: I fixed this issue a while back in my affected project. IIRC this can easily be repro'd by running `terraform show <something meaningful> | cat` inside CI, via the wrapper.

Of course, one obvious workaround is to disable the wrapper at Action setup. But that affects /every/ subsequent Terraform invocation in that Job - even the steps where having the wrapper would be beneficial!

A question and a request:

**Question**: Once the wrapper is installed, is it possible to access the underlying `terraform` CLI explicitly, via some deterministic method? If not (or even if it is, but requires a bit of string processing to find out its name and/org path), could the CLI perhaps be made available alongside the wrapper, inside $PATH under some *other* name (like `terraform-binary`, or `terraform-without-wrapper`)? The name could be chosen to minimise the chances of collision with anyone's pre-existing setup pretty easily, I suspect ... :-)

**Feature request**: please make the wrapper's output mechanism compatible with shell pipelines and redirection.

**Comment by RalphSleighK** [comment]
I just encountered this, the comment here about how to upsert a workspace will fail with the wrapper:

`if $(terraform workspace list | grep -q "${ENV}") ; then terraform workspace select ${ENV}; else terraform workspace new ${ENV}; f`

https://github.com/hashicorp/terraform/issues/16191#issuecomment-1311894688

`node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:917:11)
    at Socket._write (node:net:929:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at Object.issueCommand (/runner/_work/_temp/672d1cb4-eed3-410a-9415-f71a67d8a200/terraform:104:20)
    at Object.debug (/runner/_work/_temp/672d1cb4-eed3-410a-9415-f71a67d8a200/terraform:[373](https://github.com/KPMG-UK/sso-account/actions/runs/4243265536/jobs/7377175869#step:4:377):15)
    at /runner/_work/_temp/672d1cb4-eed3-410a-9415-f71a67d8a200/terraform:4203:8
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}`

**Comment by esolitos** [comment]
Looking [in setup-terraform.js](https://github.com/hashicorp/setup-terraform/blob/main/lib/setup-terraform.js#L86) and [in wrapper/lib/terraform-bin.js](https://github.com/hashicorp/setup-terraform/blob/v2/wrapper/lib/terraform-bin.js#L8) I would try running: `$TERRAFORM_CLI_PATH/terraform-bin show`
