### ISSUE TITLE
Output selected terraform version

### ISSUE THREAD

**Issue by F21** [hashicorp/setup-terraform#326]
It would be nice if the version of terraform that is installed can be set as an output variable, so that it can be used by other steps in a workflow.

This would be especially useful when semver is used to select a version of terraform, for example, if `terraform_version` is set to `~1.4`, and the output would contain the version that is ultimately selected, such as `1.4.6`.

**Comment by officel** [comment]
@F21 Hi!

Is this what you mean?
https://github.com/hashicorp/setup-terraform/blob/main/.github/workflows/setup-terraform.yml#L14

It does not seem necessary to create output in setup-terraform.
We can write code to get the version for other steps.

**Comment by F21** [comment]
@officel According to https://github.com/hashicorp/setup-terraform?tab=readme-ov-file#inputs, we can use semver to select the terraform version, so we don't know the version that will be installed before hand. If we can access the final version that was selected, we would be able to use it in other steps.

**Comment by officel** [comment]
Seems like there is no need to output it in the setup-terrafom since we can always use the latest or a fixed version?

But.. so.. if you just want to get the version, you can do it in just a few lines.
try this.
The key is to set wapper to false or use terraform-bin.

```bash
cat .github/workflows/terraform_version.yml
name: terraform version

on:
  workflow_dispatch:

jobs:
  tv:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions:
          - "latest"
          - "1.4"
          - "1.1"
    outputs:
      version: ${{ steps.terraform_version.outputs.version }}
    steps:
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ matrix.versions }}
      - id: terraform_version
        run: |
          echo $(terraform-bin version -json | jq -r ".terraform_version")
          echo "version=" $(terraform-bin version -json | jq -r ".terraform_version") >> "$GITHUB_OUTPUT"

```

**Comment by F21** [comment]
That works! Thanks 😄
