### ISSUE TITLE
github deprecated node16 actions, and node20 support is not yet in the roadmap for HashiCorps actions

### ISSUE THREAD

**Issue by oscar-refacton** [hashicorp/setup-terraform#366]
### TL;DR
[Node16 has been on maintenance for over a year and end-of-life since 2023-09-11](https://github.com/nodejs/Release/#end-of-life-releases). On 2023-09-22 [node16 github actions have been deprecated](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/) and to this date there's no work on adding support for node20 to HashiCorps actions.

Credit: the above was mostly copy-pasted from a similar issue for Google actions  https://github.com/google-github-actions/auth/issues/337#issue-1961228857

**Comment by t-readyroc** [comment]
Thanks for posting this issue. Just ran into it myself.

**Comment by austinvalle** [comment]
[`v3.0.0`](https://github.com/hashicorp/setup-terraform/releases/tag/v3.0.0) is released 🥳
