### ISSUE TITLE
null_resource is not getting executed always

### ISSUE THREAD

**Issue by AmudaPalani** [hashicorp/setup-terraform#37]
resource "null_resource" "getcreds" {

  triggers = {
    build_id = timestamp()
  }

  provisioner "local-exec" {
    command = "az login --service-principal -u ${var.client_id} -p ${var.client_secret} --tenant ${var.tenant_id} && az aks get-credentials --resource-group ${azurerm_resource_group.rg.name} --name ${azurerm_kubernetes_cluster.aks.name}"
  }
}

Bug: null_resource is not getting executed always. This is getting executed first time and then second time it says refreshing state even though triggger is set to run by current timestamp. Seeing this issue only in github actions. It works in Jenkins.

**Comment by bflad** [comment]
This appears to have been a potential bug in an older version of Terraform or the null provider, not setup-terraform itself. If you are still running into issues with this particular setup with recent versions of Terraform, null provider, and setup-terraform, please raise a new bug report and we can take a fresh look.
