### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by wanisfahmyDE** [hashicorp/setup-terraform#370]
Hi there,

We are using the `hashicorp/setup-terraform@v2` but it's quite old (released nov 2022) and with terraform 1.6, setting the `terraform_wrapper:true` actually doesn't work on GH runners (ubuntu-latest) anymore.

When switching to `hashicorp/setup-terraform@main` everything worked as expected but we'd prefer using a pinned version to avoid future unexpected behaviour.

Is there a plan to do a release soon for the action?

Many thanks

**Comment by austinvalle** [comment]
Hey there @wanisfahmyDE 👋🏻 ,

[`v3.0.0`](https://github.com/hashicorp/setup-terraform/releases/tag/v3.0.0) has just been released 🥳

**Comment by wanisfahmyDE** [comment]
amazing, thanks @austinvalle for the quick help!
