### ISSUE TITLE
Variable tf_actions_working_dir is not specified in actions.yml

### ISSUE THREAD

**Issue by Hellseher** [hashicorp/setup-terraform#40]
Hi,

The variable `tf_actions_working_dir` used in README example and not specified in action.yml
https://github.com/hashicorp/setup-terraform/blame/master/README.md#L86

Related question: how to set default directory for Terraform cli in this action?

It's in archived project and not available in this one
https://github.com/hashicorp/terraform-github-actions/blob/master/action.yml

Thanks.

**Comment by nic-hima** [comment]
@Hellseher I noticed this behavior of this and other variables from https://github.com/hashicorp/terraform-github-actions too and have used the `working-directory:` parameter.

`working-directory` only works for `steps` that use `run:` statements. (which btw is how most examples of actions using https://github.com/hashicorp/setup-terraform change specify what directory to run these `steps`)

You can use this inline with a `step` like:
<pre><code>
      - name: Setup - Terraform CLI
        uses: hashicorp/setup-terraform@v1.1.0
        with:
          terraform_version: ${{ env.tf_version }}

      - name: "Run - Terraform Init"
        id: init
        run: terraform init -no-color -input=false
         <b>working-directory: ./path/to/dir</b>
</code></pre>

OR if you have to use the same `working-directory:` in all `steps` within a `job`. Here is an example of setting a default working directory for all `steps` that execute `run:`

```
jobs:
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./path/to/dir
```

----

It seems like this repo https://github.com/hashicorp/setup-terraform favors using the `run:` statement, whereas https://github.com/hashicorp/terraform-github-actions examples don't use `run:` statements, instead it passes in args using `with:` statements. I haven't found anywhere that this is explicitly called out, but this repo https://github.com/hashicorp/setup-terraform only seems to have 4 possible `with:` variables. 
- cli_config_credentials_hostname'
- 'cli_config_credentials_token'
- 'terraform_version'
- 'terraform_wrapper'

The below snippet was from when I was testing https://github.com/hashicorp/setup-terraform using the variables described in https://github.com/hashicorp/terraform-github-actions
```
##[warning]Unexpected input(s) 'tf_actions_version', 'tf_actions_subcommand', 'tf_actions_working_dir', 'tf_actions_comment', valid inputs are ['cli_config_credentials_hostname', 'cli_config_credentials_token', 'terraform_version', 'terraform_wrapper']
```

and that error message is how I figured out the difference in variables between these two repos.

Hope this comment was informative and helped you out :)

**Comment by rjudin** [comment]
Setting up default working directory produce errors as mentioned in comment 
https://github.com/hashicorp/setup-terraform/issues/40#issuecomment-685187761

If skipping `working-directory` is not an option, try with 
`terraform_wrapper = false` (unfortunately that will disable direct disired output https://github.com/hashicorp/setup-terraform#outputs)

Issue needs to be addressed. Who able to help with that?

**Comment by sheeeng** [comment]
How/where does `working-directory: ${{ env.tf_actions_working_dir }}` is being properly defined?

The sample code is taken from this [commit](https://github.com/hashicorp/setup-terraform/tree/633666f66e0061ca3b725c73b2ec20cd13a8fdd1).

**Comment by bflad** [comment]
Hi folks 👋

GitHub Actions provides multiple options for setting the working directory for running commands:

- [`defaults.run`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defaultsrun)
- [`jobs.<id>.defaults.run](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrun)
- [`jobs.<id>.steps[*].working-directory`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsworking-directory)

Terraform also provide the [`chdir` command flag](https://developer.hashicorp.com/terraform/cli/commands#switching-working-directory-with-chdir), if necessary.

If you have further questions with how to use this action or GitHub Actions in general, my best recommendation would be to submit a topic in the [Terraform section of HashiCorp Discuss](https://discuss.hashicorp.com/c/terraform-core/27) or [Actions section of GitHub Community Discussions](https://github.com/orgs/community/discussions/categories/actions).
