### ISSUE TITLE
Terraform Plan Exitcode Not 2 as expected when there's updates.

### ISSUE THREAD

**Issue by Dipak-Mistry-WTW** [hashicorp/setup-terraform#417]
When using Githust hosted runner the exitcode is set to 0 from Terraform plan step even when there are updates. At the end of the plan step I see:

```
##[debug]Saved the plan to: dev.tfplan
##[debug]
##[debug]To perform exactly these actions, run the following command to apply:
##[debug]    terraform apply "dev.tfplan"
##[debug]Releasing state lock. This may take a few moments...
##[debug]
##[debug]Set output stderr = 
##[debug]Set output exitcode = 2
##[debug]Set output exitcode = 0
##[debug]Finishing: Terraform Plan

```

Then in the Complete Job step I see:

```
##[debug]Starting: Complete job
Evaluate and set job outputs
##[debug]Evaluating: steps.tf-plan.outputs.exitcode
##[debug]Evaluating Index:
##[debug]..Evaluating Index:
##[debug]....Evaluating Index:
##[debug]......Evaluating steps:
##[debug]......=> Object
##[debug]......Evaluating String:
##[debug]......=> 'tf-plan'
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'outputs'
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'exitcode'
##[debug]=> '0'
##[debug]Result: '0'
Set output 'tfplanExitCode'
Cleaning up orphan processes
##[debug]Finishing: Complete job
```

The next job needs exitcode of 2 to run the terraform apply step.

**Comment by np5** [comment]
The wrapper that is installed by default [masks the exit code](https://github.com/hashicorp/setup-terraform/blob/3235006f3a5bc0e29fb49e41401c5bff62c4d885/wrapper/terraform.js#L39-L52). You can use the action with the `terraform_wrapper: false` option, or you can change your tests to check for the outputs that the wrapper is already  setting up.

**Comment by Dipak-Mistry-WTW** [comment]
@np5 Thanks - I added the option to set the wrapper to false. That's all I needed.
