### ISSUE TITLE
terraform removed in Ubuntu 24.04 image

### ISSUE THREAD

**Issue by vasireddy99** [hashicorp/setup-terraform#448]
<img width="824" alt="image" src="https://github.com/user-attachments/assets/8df88e27-e4c0-4627-bdd9-4978d1bb74c0">

can someone explain what does this removal means to the setup-terraform in ubuntu-latest breaking changes.

https://github.blog/changelog/2024-11-05-notice-of-breaking-changes-for-github-actions/#ubuntu-latest-upcoming-breaking-changes

**Comment by austinvalle** [comment]
Hey there @vasireddy99 👋🏻 ,

Prior to the Ubuntu `24.04` image, Github runners had the latest version of Terraform automatically installed, see the [`22.04` image](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#tools). The removal of that pre-installed version in `24.04` would only affect your workflow if you didn't use `setup-terraform` and were relying on that latest version of Terraform being installed by default in your github runner.

An example of that might be something like the CI workflow for the random Terraform provider, which used to rely on the latest version of Terraform being installed to generate it's documentation. Using the new runners you can just use `setup-terrafrom` to install the latest version: https://github.com/hashicorp/terraform-provider-random/pull/611 .

So for users of this GitHub action, no changes should be necessary 👍🏻
