### ISSUE TITLE
The 'set-env' command is deprecated

### ISSUE THREAD

**Issue by baski-accenture** [hashicorp/setup-terraform#65]
Getting below message with hashicorp/setup-terraform@v1

Error: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by khorwood** [comment]
Was fixed in #63, v1 tag hasn't been bumped yet though.
#64

**Comment by baski-accenture** [comment]
@khorwood thanks do you know when this is planned?

**Comment by khorwood** [comment]
@baski-accenture I'm not a maintainer, hopefully soon, or I'll have to switch to `master`.

**Comment by adamrushuk** [comment]
I've just pinned to `v1.2.1` until this is fixed:

`uses: hashicorp/setup-terraform@v1.2.1`

**Comment by baski-accenture** [comment]
@adamrushuk yes i did the same but also wondering when the new versions would be available with v1

**Comment by baski-accenture** [comment]
@khorwood thanks. I used @1.2.1 for now

**Comment by aeschright** [comment]
Sorry about that, I didn't realize I would need to do it manually. Have another try and if everything looks good I'll close this.

**Comment by baski-accenture** [comment]
@aeschright Do you mean v1 is already now pointing to v1.2.1? We already confirmed that with v1.2.1 specifically mentioned, there are no more error messages.

**Comment by aeschright** [comment]
Yes, the `v1` tag now points to `1.2.1`.

**Comment by cwi-tyrone** [comment]
I can confirm that `hashicorp/setup-terraform@v1` no longer produces deprecated warnings.

**Comment by adamrushuk** [comment]
Thanks for fixing! 👍🏼
