### ISSUE TITLE
Semver for Terraform v0.14.x Isn't pulling latest version

### ISSUE THREAD

**Issue by seano-vs** [hashicorp/setup-terraform#69]
Essentially as the title states. I don't know if the documentation needs updating or if I am reading the [semver comments in the code incorrectly](https://github.com/hashicorp/setup-terraform/blob/ccd38093bb84fe21709c58bcbbebec1b9861a435/dist/index.js#L6237), but as it stands specifying 0.14.x fails. 

It seems that the versions in [Hashi's release list](https://releases.hashicorp.com/terraform/index.json) follows the standard well enough. Apologies ahead of time if this is user error on my part!

I'll dive further into it and try to create a PR if I have some extra time.

**Comment by alexjurkiewicz** [comment]
The action ignores pre-release versions to prevent people accidentally
updating to unexpected versions. A way to override this would be nice
though...

**Comment by aeschright** [comment]
0.14 is now GA so I'll close this. In the future, you can set a pre-release version explicitly, or give a semver range that includes the pre-release tag (like `0.14.0-rc1`). Details on how those ranges work are here: https://github.com/npm/node-semver#prerelease-tags
