### ISSUE TITLE
Looks like the latest release (15 mins ago) has some issues?

### ISSUE THREAD

**Issue by TheMacStack** [hashicorp/setup-terraform#75]
```
Run hashicorp/setup-terraform@v1
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'asn1.js'
Require stack:
- /home/runner/work/_actions/hashicorp/setup-terraform/v1/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at o (/home/runner/work/_actions/hashicorp/setup-terraform/v1/dist/index.js:6804:200)
    at /home/runner/work/_actions/hashicorp/setup-terraform/v1/dist/index.js:6804:391
    at Object.<anonymous> (/home/runner/work/_actions/hashicorp/setup-terraform/v1/dist/index.js:37880:27)
    at Object.108.../../config (/home/runner/work/_actions/hashicorp/setup-terraform/v1/dist/index.js:38446:4)
    at o (/home/runner/work/_actions/hashicorp/setup-terraform/v1/dist/index.js:6804:340)
    at /home/runner/work/_actions/hashicorp/setup-terraform/v1/dist/index.js:6804:391 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/hashicorp/setup-terraform/v1/dist/index.js'
  ]
}
```
on side note how can i pin this to an older release?

**Comment by wyTrivail** [comment]
is v1 pointed to v1.3.0 now? i thought the v1 tag is immutable and looks like it is not?

**Comment by jhindulak** [comment]
You can pin the previous release with the example below until this is fixed.
```yaml
- name: HashiCorp - Setup Terraform
  uses: hashicorp/setup-terraform@v1.2.1
```

**Comment by kyeah** [comment]
It looks like you need to pin the full version, not just v1. e.g. `setup-terraform@v1.2.1` seems to fix it for us.

**Comment by joshgubler** [comment]
Please force push v1 back to d22444889af304a44b997011fbabb81ff705a7b4 until this is fixed.

**Comment by GaryGSC** [comment]
@aeschright, could we get [`v1`](https://github.com/hashicorp/setup-terraform/releases/tag/v1) moved back to v1.2.1 while this gets sorted out?

**Comment by aeschright** [comment]
Done 👍  I'll figure out why that's happening – I saw something similar when `npm install` was missing from the steps.

**Comment by khitrenovich** [comment]
I see the same error with v1.3.1 too.

**Comment by aeschright** [comment]
Thanks for your patience while I sorted this out! v1.3.2 should have fully resolved the issue and I've tested it, but I'll wait for others to confirm before I move the v1.0 tag.

**Comment by Ameausoone** [comment]
Fixed with https://github.com/hashicorp/setup-terraform/releases/tag/v1.3.2 thx
