### ISSUE TITLE
How to leverage VCS Driven Plan yet output the planned changes to the pull request?

### ISSUE THREAD

**Issue by sheldonhull** [hashicorp/setup-terraform#88]
My scenario:

- I have a Pull Request opened.
- I want the change to be in the pull request (similar to Atlantis or how the demos here show the plan output from GitHub Actions). This allows immediate feedback for those not even using Terraform Cloud (such as a developer submitting a quick config change, but not managing the Terraform Cloud workspaces).
- Once the approval occurs, I want the plan to be queued just like in VCS driven approach, but still allow the choice to require approval in Terraform Cloud.

Right now, it seems I have to choose between:

1. API Driven to get the great feedback in the pull request
	2. Misses the nice integration and protection from VCS connection.
2. Use VCS driven approach
	3. Con: No way to get the plan changes output to the pull request that I see. 

So the gist of the question: 

How can I ideally leverage the workflow of VCS driven terraform plans, while still providing plan change output to the pull request?

**Comment by debragail** [comment]
I also am curious to have more documentation around this and returns.

**Comment by bflad** [comment]
Hi @sheldonhull  👋 Thank you for raising this and sorry for the delayed response. For you or anyone here, my best recommendation would be to submit a topic in the [Terraform section of HashiCorp Discuss](https://discuss.hashicorp.com/c/terraform-core/27), where there are many more people asking and answering usage questions such as these. If you have a specific feature request for the `setup-terraform` GitHub Action, please create a new issue and we will take a fresh look.
