### ISSUE TITLE
Request to update starter workflow with environments

### ISSUE THREAD

**Issue by imjohnbo** [hashicorp/setup-terraform#89]
Hello! 👋 In order to provide deployment tracking and exemplify good usage patterns, would this team be able to PR the [Terraform starter workflow](https://github.com/actions/starter-workflows/blob/main/ci/terraform.yml#L57) with `environments: production` on the main (ok, only 😄) job? Thanks for taking a look!

More here:
- [Docs](https://docs.github.com/en/free-pro-team@latest/actions/reference/environments), [more docs](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idenvironment)
- [Blog post](https://github.blog/changelog/2020-12-15-github-actions-environments-environment-protection-rules-and-environment-secrets-beta/)

**Comment by bflad** [comment]
Hi @imjohnbo 👋 Thank you for this feature request. Looks like this already happened: https://github.com/actions/starter-workflows/blob/16ea338f2a3f14f58188c8a968effcd5b954543f/deployments/terraform.yml#L59
