### ISSUE TITLE
Specifying working-directory breaks wrapper

### ISSUE THREAD

**Issue by phyber** [hashicorp/setup-terraform#90]
Hi,

I have a repository with the following kind of structure:

```
.
├── account_a
│   └── main.tf
└── account_b
    └── main.tf
```

Github Actions are setup to run Terraform in specific account directories when changes occur in those directories:
```yaml
on:
  push:
    paths:
      - 'account_a/**.tf'
```

Due to all Terraform commands having to take place in the specific account directory, it makes sense to use the `working-directory` key in the run steps. We can set that as a default in our actions configuration with:

```yaml
defaults:
  run:
    working-directory: 'account_a'
```

This should all work nicely, except it somehow breaks the `setup-terraform` action (at least when using the wrapper). This appears to be because the wrapper script is using the `working-directory` for something itself.

A broken run will look like this:

```
# Setup Terraform step
Run hashicorp/setup-terraform@v1
  with:
    terraform_version: 0.14.4
    terraform_wrapper: true
    cli_config_credentials_hostname: app.terraform.io
/usr/bin/unzip -q /home/runner/work/_temp/957e7d2a-3383-4974-b05b-d3b0d008439c

# Terraform Init step
Run terraform init
  terraform init
  shell: /bin/bash -e {0}
  env:
    TERRAFORM_CLI_PATH: /home/runner/work/_temp/33eb65dd-531d-4107-a24f-c2b883c538f2
Error: No such file or directory
```

While a run that doesn't specify a `working-directory` will look as follows:

```
# Setup Terraform step
Run hashicorp/setup-terraform@v1
  with:
    terraform_version: 0.14.4
    terraform_wrapper: true
    cli_config_credentials_hostname: app.terraform.io
/usr/bin/unzip -q /home/runner/work/_temp/40143050-2d09-4911-8827-84146037bb19

# Terraform Init step
Run terraform init
  terraform init
  shell: /bin/bash -e {0}
  env:
    TERRAFORM_CLI_PATH: /home/runner/work/_temp/de0eaa9b-afb4-47f6-b846-9eb59f87a70c
/home/runner/work/_temp/de0eaa9b-afb4-47f6-b846-9eb59f87a70c/terraform-bin init
Terraform initialized in an empty directory!

The directory has no Terraform configuration files. You may begin working
with Terraform immediately by creating Terraform configuration files.
```

The empty directory warning there is because the root of the repository contains no Terraform, it's all in subdirectories.

I am aware I could simply not specify a `working-directory` default and just `cd` to the appropriate directories as part of my `run` commands, however, this is not as nice as being able to just specify the `working-directory` a single time.

My guess here is that something is trying to run the wrapper command from a relative path, but I'm nor familiar enough with JavaScript to confirm this. I did find the `RUNNER_DEBUG` environment toggle, but sadly it gave no additional insight.

**Comment by phyber** [comment]
Apologies for this, I believe I've found the breakage and there is no problem with the wrapper.

Sorry again for the confusion.

**Comment by JKetelaar** [comment]
Could you share the breakage and help others on how to solve this @phyber?

**Comment by phyber** [comment]
@JKetelaar Embarassingly, the issue here was that the GitHub Actions workflow was missing a `checkout` step, so there were no directories for `working-directory` to `cd` to.

**Comment by JKetelaar** [comment]
Thanks for the elaboration! That, embarrassingly, helped me as well...
